version: '3'

services:
  nginx-proxy:  
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_net

  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - "VIRTUAL_HOST=backend.51.38.184.194"
    networks:
      - my_net

  frontend:
    build: 
      context: ./frontend-app
    links:
      - backend
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=web.51.38.184.194"
    depends_on:
      - mongo
      - backend
    networks:
      - my_net
networks:
  my_net:
