version: '3'

services:
  traefik:
    images: traefik:latest
    command: --docker --docker.domain=hakase-labs.io
    ports:
      - 80:80
      - 443:443
    networks: 
      - my_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:traefik.hakase-labs.io"
      - "traefik.port=8080"
    container_name: traefik
    restart: always
  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_net

  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - my_net

  frontend:
    build: 
      context: ./frontend-app
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - mongo
      - backend
    networks:
      - my_net
networks:
  my_net:
    external: true
