version: '3'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/traefik.toml
    container_name: traefik

  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - local_network
    container_name: mongo

  backend:
    build: 
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.frontend.rule=Host:backend.serantes.pro"
      - "traefik.basic.port=3000"
    volumes:
      - $PWD/ssl_certs/server:/user/src/app/server/config/ssl_certs
    depends_on:
      - mongo
    networks:
      - local_network
      - web
    container_name: backend

  frontend:
    build: 
      context: ./frontend-app
    links:
      - backend
    labels: 
      - "traefik.basic.frontend.rule=Host:serantes.pro"
      - "traefik.basic.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - local_network
      - web
    volumes:
      - $PWD/ssl_certs/frontend-app:/etc/nginx/ssl
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web
networks:
  web:
    external: true
  local_network: