version: '3'

services:
  traefik:
    image: traefik:latest
    command: --api --docker --docker.domain=serantes.pro
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    labels:
      - "traefik.basic.frontend.rule=Host:traefik.serantes.pro"
      - "traefik.basic.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
    container_name: traefik

  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - web
    container_name: mongo

  backend:
    build: 
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=Host:backend.serantes.pro"
      - "traefik.port=3000"
    volumes:
      - $PWD/ssl_certs/server:/user/src/app/server/config/ssl_certs
    depends_on:
      - mongo
    networks:
      - web
    container_name: backend

  frontend:
    build: 
      context: ./frontend-app
    links:
      - backend
    ports:
      - 9000:80
    labels:
      - "traefik.backend=web"
      - "traefik.basic.frontend.rule=Host:web.serantes.pro"
      - "traefik.basic.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/ssl_certs/frontend-app:/etc/nginx/ssl
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web
networks:
  web:
    external: true