version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - local_network

  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - $PWD/ssl_certs:/user/src/app/server/config/ssl_certs
    networks:
      - local_network

  frontend:
    build: 
      context: ./frontend-app
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongo
      - backend
    networks:
      - local_network
    volumes:
      - $PWD/ssl_certs:/etc/nginx/ssl
      - $PWD/nginx_conf:/etc/nginx/conf.d
networks:
  local_network:
