defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
    [web.auth.basic]
    users = ["admin:$apr1$9wVQrngs$ZySiKy7Ola2NcNx0OGD121"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
    
[acme]
email = "test@serantes.pro"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false