debug = false

[web]
address = ":8080"
  [web.auth.basic]
   users = ["admin:$apr1$jc0xKaqs$1haUJKtZKmuuBiOd.1R891"]

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "serantes.pro"
watch = true